version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pg
    versions:
    - ">= 1.a, < 2"
  - dependency-name: rails
    versions:
    - ">= 5.a, < 6"
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: rubocop-performance
    versions:
    - 1.10.1
